services:
  rabbitmq:
    image: 'rabbitmq:3.13-rc-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro